language: ruby

bundler_args: --without production

services:
  - postgresql

before_script:
  - export CODACY_PROJECT_TOKEN=6c9ad7759c7d4b54addbe6fcda0c83f2
  - psql -c 'create database database_test;' -U postgres

after_script:
  - rails test
  - bundle exec rspec